### ISSUE TITLE
Feedback Request: SEC-01 Network detection

### ISSUE THREAD

**Issue by Rolfsijtema** [TechGrounds-Cloud8/cloud8-Rolfsijtema#10]
**Feedback Request [SEC-01 Network Detection ]**
Permalink to file: [[LINK](https://github.com/TechGrounds-Cloud8/cloud8-Rolfsijtema/blob/a9ed3c467177d3ad7b872a8f6062121b661a2921/week2cloud8/Sec-1%20Network%20Detection.md)]

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by sasudi90** [comment]
**Summary**
- Does the summary describe the subject matter fully? y 
- Is the summary written in own words? y 
- Is there crucial information missing in the summary? n
- Is the description clear enough? y 

**Key Terminology**
- Are there missing key terms? n 
- Are the key terms explained well? y 

**Sources**
- Are the sources mentioned? y 
- Are the mentioned sources correct? y

**Excercise**
(Where applicable)
- Is the result correct? y
- Are the experienced problems and solutions described well? edit experienced problems :)

**Comment by Acron0815** [comment]
This theoretical assignment is apparently understood, and does not seem to be the most difficult.

**Comment by pprasing** [comment]
**Summary**
- Does the summary describe the subject matter fully? yes
- Is the summary written in own words?yes
- Is there crucial information missing in the summary? no
- Is the description clear enough? yes

**Key Terminology**
- Are there missing key terms? no
- Are the key terms explained well? yes

**Sources**
- Are the sources mentioned? yes
- Are the mentioned sources correct? yes

**Excercise**
(Where applicable)
- Is the result correct? yes, except there is no screenshot of nmap
- Are the experienced problems and solutions described well? yes
