### ISSUE TITLE
Feedback Request: 

### ISSUE THREAD

**Issue by Rolfsijtema** [TechGrounds-Cloud8/cloud8-Rolfsijtema#11]
**Feedback Request [Sec-02 Firewall]**
Permalink to file: [[LINK](https://github.com/TechGrounds-Cloud8/cloud8-Rolfsijtema/blob/1926a18938164cf708cc2b1a119d1f78e42b7693/week2cloud8/Sec-02%20Firewalls.md)]

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Acron0815** [comment]
I see a Cum laude coming!

PS Sorry about the short response, I'm still battling with (GitHub vs Visual Studio) issues

**Comment by pprasing** [comment]
**Summary**
- Does the summary describe the subject matter fully? yes
- Is the summary written in own words? yes
- Is there crucial information missing in the summary? no
- Is the description clear enough? yes

**Key Terminology**
- Are there missing key terms? no
- Are the key terms explained well? yes

**Sources**
- Are the sources mentioned? yes
- Are the mentioned sources correct? yes

**Excercise**
(Where applicable)
- Is the result correct?yes 
- Are the experienced problems and solutions described well? yes great job!

**Comment by sasudi90** [comment]
**Summary**
- Does the summary describe the subject matter fully? y
- Is the summary written in own words? y
- Is there crucial information missing in the summary? n
- Is the description clear enough? y

**Key Terminology**
- Are there missing key terms? n
- Are the key terms explained well? y

**Sources**
- Are the sources mentioned? y 
- Are the mentioned sources correct?  y

**Excercise**
(Where applicable)
- Is the result correct? y
- Are the experienced problems and solutions described well? y
