### ISSUE TITLE
Feedback Request: SEC-07 Passwords

### ISSUE THREAD

**Issue by Rolfsijtema** [TechGrounds-Cloud8/cloud8-Rolfsijtema#16]
**Feedback Request [SEC-07 Passwords]**
Permalink to file: [[LINK](https://github.com/TechGrounds-Cloud8/cloud8-Rolfsijtema/blob/f81b414ddeea2ea0734df70b6682e204d7308a84/week3cloud8/SEC-07%20Passwords.md)]

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by sasudi90** [comment]
**Summary**
- Does the summary describe the subject matter fully? y
- Is the summary written in own words? y
- Is there crucial information missing in the summary? n
- Is the description clear enough? y

**Key Terminology**
- Are there missing key terms? n
- Are the key terms explained well? y

**Sources**
- Are the sources mentioned? y
- Are the mentioned sources correct? y

**Excercise**
(Where applicable)
- Is the result correct? y
- Are the experienced problems and solutions described well? y

**Comment by pprasing** [comment]
**Summary**
- Does the summary describe the subject matter fully? yes
- Is the summary written in own words? yes
- Is there crucial information missing in the summary? no its complete
- Is the description clear enough? yes

**Key Terminology**
- Are there missing key terms? no 
- Are the key terms explained well? yes

**Sources**
- Are the sources mentioned? yes
- Are the mentioned sources correct? yes

**Excercise**
(Where applicable)
- Is the result correct? yes, good job!
- Are the experienced problems and solutions described well? yes

**Comment by Acron0815** [comment]
Summary

Does the summary describe the subject matter fully? ja
Is the summary written in own words? ja
Is there crucial information missing in the summary? nein
Is the description clear enough? ja
Key Terminology

Are there missing key terms? nein
Are the key terms explained well? ja
Sources

Are the sources mentioned? ja
Are the mentioned sources correct? ja
Excercise
(Where applicable)

Is the result correct? ja
Are the experienced problems and solutions described well? ja
