### ISSUE TITLE
Feedback Request: AWS-01 Global Infrastructure

### ISSUE THREAD

**Issue by Rolfsijtema** [TechGrounds-Cloud8/cloud8-Rolfsijtema#18]
**Feedback Request [AWS Global Infrastructure]**
Permalink to file: [[LINK](https://github.com/TechGrounds-Cloud8/cloud8-Rolfsijtema/blob/19f8ef867d561d18cc96851161e75d7a65c98695/week4cloud8/AWS-01%20Global%20Infrastructure.md)]

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Killian97** [comment]
Assignment done, but i would explain a bit more. from your answers i can believe you know what everything means but do you also know what they actually include? for example what do regions offer. 

well done but i would personnaly like to see more explanation of a subject. (thinking in the way of a future employer that would read this)

**Comment by QuincyTjia** [comment]
**Summary**
- Does the summary describe the subject matter fully? **It does but could be more extensive**
- Is the summary written in own words? **Yes**
- Is there crucial information missing in the summary? **See the first point**
- Is the description clear enough? **It is**

**Key Terminology**
- Are there missing key terms? **No**
- Are the key terms explained well? **Its a bit basic, but if you know what they mean then its allright**

**Sources**
- Are the sources mentioned? **Yes**
- Are the mentioned sources correct? **Yes**

**Excercise**
(Where applicable)
- Is the result correct? **Yes**
- Are the experienced problems and solutions described well? **Yes**

**Comment by Rolfsijtema** [comment]
Thanx for the notes, i added some deeper info about AWS Regions...

**Comment by archana-sekarr** [comment]
**Summary**
- Does the summary describe the subject matter fully? yes
- Is the summary written in own words? yes
- Is there crucial information missing in the summary? no
- Is the description clear enough? yes

**Key Terminology**
- Are there missing key terms? no
- Are the key terms explained well? the key terminologies could have been explained in detail

**Sources**
- Are the sources mentioned? yes
- Are the mentioned sources correct? yes

**Excercise**
(Where applicable)
- Is the result correct? yes
- Are the experienced problems and solutions described well? yes

**Comment by sasudi90** [comment]
**Summary**
- Does the summary describe the subject matter fully? y
- Is the summary written in own words? y
- Is there crucial information missing in the summary? y
- Is the description clear enough? y

**Key Terminology**
- Are there missing key terms? n
- Are the key terms explained well?  im missing some depth in key terminology

**Sources**
- Are the sources mentioned? y
- Are the mentioned sources correct? y

**Excercise**
(Where applicable)
- Is the result correct? y
- Are the experienced problems and solutions described well? y
