### ISSUE TITLE
Feedback Request: AWS-02 Pricing

### ISSUE THREAD

**Issue by Rolfsijtema** [TechGrounds-Cloud8/cloud8-Rolfsijtema#19]
**Feedback Request [AWS-02 Pricing]**
Permalink to file: [[LINK](https://github.com/TechGrounds-Cloud8/cloud8-Rolfsijtema/blob/a985f709cc5e4d21d5d20d1fb158c54c728c948b/week4cloud8/AWS-02%20Pricing.md)]

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by sasudi90** [comment]
**Summary**
- Does the summary describe the subject matter fully? y
- Is the summary written in own words? y
- Is there crucial information missing in the summary? n 
- Is the description clear enough? y

**Key Terminology**
- Are there missing key terms?  n
- Are the key terms explained well? explain the pricing model in more detail please ( pay as you go, save when u commit, pay less by using more, benefit from massive economies of scale)

**Sources**
- Are the sources mentioned? y
- Are the mentioned sources correct? y

**Excercise**
(Where applicable)
- Is the result correct? y
- Are the experienced problems and solutions described well? overcome challenges?

**Comment by QuincyTjia** [comment]
**Summary**
- Does the summary describe the subject matter fully? **Yes**
- Is the summary written in own words? **yes, but its missing a word at the end of the line**
- Is there crucial information missing in the summary? **No**
- Is the description clear enough? **See the second comment**

**Key Terminology** 
- Are there missing key terms? **No**
- Are the key terms explained well? **Could be better, its easier for yourself if you explain it in more details. This will make it easier to search for it in the future**

**Sources**
- Are the sources mentioned? **Yes**
- Are the mentioned sources correct? **Yes**

**Excercise**
(Where applicable)
- Is the result correct? **Yes**
- Are the experienced problems and solutions described well? **No, you didn't describe it**
