### ISSUE TITLE
Feedback Request: Git en github1

### ISSUE THREAD

**Issue by Rolfsijtema** [TechGrounds-Cloud8/cloud8-Rolfsijtema#2]
**Feedback Request git en github**
Permalink to file: [git en github1](https://github.com/TechGrounds-Cloud8/cloud8-Rolfsijtema/blob/main/week1cloud8/git01%20git%20en%20github.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Killian97** [comment]
snel gekeke zag er goed uit

**Comment by abdeslamazhir** [comment]
Summary

Does the summary describe the subject matter fully? yes
Is the summary written in own words? yes
Is there crucial information missing in the summary? no
Is the description clear enough? yes
Key Terminology

Are there missing key terms? no
Are the key terms explained well? yes
Sources

Are the sources mentioned? yes
Are the mentioned sources correct? yes
Excercise
(Where applicable)

Is the result correct? yes
Are the experienced problems and solutions described well? yes

**Comment by sasudi90** [comment]
ziet er goed uit! geen op- of aanmerkingen
