### ISSUE TITLE
Feedback Request: AWS-04 Core Services

### ISSUE THREAD

**Issue by Rolfsijtema** [TechGrounds-Cloud8/cloud8-Rolfsijtema#21]
**Feedback Request [AWS-04 Core Services]**
Permalink to file: [[LINK](https://github.com/TechGrounds-Cloud8/cloud8-Rolfsijtema/blob/d55643ee4f9152b283a0013c0efc2ac701b598b1/week4cloud8/AWS-04%20Core%20Services.md)]

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Killian97** [comment]
well explained, everyting seems to be in there

**Comment by archana-sekarr** [comment]
**Summary**
- Does the summary describe the subject matter fully? yes
- Is the summary written in own words? yes
- Is there crucial information missing in the summary? no
- Is the description clear enough? yes

**Key Terminology**
- Are there missing key terms? no
- Are the key terms explained well? yes

**Sources**
- Are the sources mentioned? yes
- Are the mentioned sources correct? yes

**Excercise**
(Where applicable)
- Is the result correct? yes
- Are the experienced problems and solutions described well? yes, very clear explanations
