### ISSUE TITLE
Feedback Request: AWS-05 S3

### ISSUE THREAD

**Issue by Rolfsijtema** [TechGrounds-Cloud8/cloud8-Rolfsijtema#22]
**Feedback Request [AWS-05 S3]**
Permalink to file: [[LINK](https://github.com/TechGrounds-Cloud8/cloud8-Rolfsijtema/blob/a5c2c36ac50d35603b04e97719f9603f756875b0/week4cloud8/AWS-05%20S3.md)]

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Killian97** [comment]
well done results look good but maybe share some more screenshots of your AWS dashboard. so everyone can see the "behind the screens" aswell

**Comment by QuincyTjia** [comment]
**Summary**
- Does the summary describe the subject matter fully? **Yes**
- Is the summary written in own words? **Yes**
- Is there crucial information missing in the summary? **No**
- Is the description clear enough? **Yes**

**Key Terminology**
- Are there missing key terms? **No**
- Are the key terms explained well? **Yes**

**Sources**
- Are the sources mentioned? **Yes**
- Are the mentioned sources correct? **Yes**

**Excercise**
(Where applicable)
- Is the result correct? **Yes**
- Are the experienced problems and solutions described well? **Yes**
