### ISSUE TITLE
Feedback Request: AWS-06 Elastic Compute Cloud (EC2)

### ISSUE THREAD

**Issue by Rolfsijtema** [TechGrounds-Cloud8/cloud8-Rolfsijtema#23]
**Feedback Request [AWS-06 Elastic Compute Cloud (EC2)]**
Permalink to file: [[LINK](https://github.com/TechGrounds-Cloud8/cloud8-Rolfsijtema/blob/a6738221fbb88aad9bea5cfb48228ebb726934bc/week4cloud8/AWS-06%20EBS.md)]

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Killian97** [comment]
You need to re read about security groups, what you have said is not correct.
i see you copy pasted from the assignment to explain the exercise but you cant copy paste code into markdown because it will trigger the code. Think you need to re read about markdown a bit.

assignment itself completed succesfully

**Comment by sasudi90** [comment]
**Summary**
- Does the summary describe the subject matter fully? y
- Is the summary written in own words? y
- Is there crucial information missing in the summary?  n
- Is the description clear enough? y

**Key Terminology**
- Are there missing key terms? y, what about user data, ami? :)
- Are the key terms explained well? y

**Sources**
- Are the sources mentioned? y
- Are the mentioned sources correct? y

**Excercise**
(Where applicable)
- Is the result correct? y
- Are the experienced problems and solutions described well? y

**Comment by Rolfsijtema** [comment]
Fixed info about Security Groups ;)
