### ISSUE TITLE
Feedback Request: AWS-07 EBS

### ISSUE THREAD

**Issue by Rolfsijtema** [TechGrounds-Cloud8/cloud8-Rolfsijtema#24]
**Feedback Request [AWS-07 EBS]**
Permalink to file: [link](https://github.com/TechGrounds-Cloud8/cloud8-Rolfsijtema/blob/93efcb765fd33228e2325bb5bd5ecf9d411b705b/week4cloud8/AWS-07%20EBS.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Killian97** [comment]
nice, good to see the time spend teamworking paid out

**Comment by QuincyTjia** [comment]
**Summary**
- Does the summary describe the subject matter fully? **Yes**
- Is the summary written in own words? **Yes**
- Is there crucial information missing in the summary? **No**
- Is the description clear enough? **Yes**

**Key Terminology**
- Are there missing key terms? **No**
- Are the key terms explained well? **Yes**

**Sources**
- Are the sources mentioned? **Yes**
- Are the mentioned sources correct? **Yes**

**Excercise**
(Where applicable)
- Is the result correct? **Yes**
- Are the experienced problems and solutions described well? **Yes**
