### ISSUE TITLE
Feedback Request: AWS10 VPC

### ISSUE THREAD

**Issue by Rolfsijtema** [TechGrounds-Cloud8/cloud8-Rolfsijtema#27]
**Feedback Request [AWS10 VPC]**
Permalink to file: [[LINK](https://github.com/TechGrounds-Cloud8/cloud8-Rolfsijtema/blob/5d968008efa4507462c4ffa276cf6065d5083687/week5cloud8/AWS-10%20VPC.md)]

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Killian97** [comment]
assignment completed

**Comment by QuincyTjia** [comment]
**Summary**
- Does the summary describe the subject matter fully? yes
- Is the summary written in own words? yes
- Is there crucial information missing in the summary? no
- Is the description clear enough? yes

**Key Terminology**
- Are there missing key terms? no
- Are the key terms explained well? yes

**Sources**
- Are the sources mentioned? no
- Are the mentioned sources correct? no

**Excercise**
(Where applicable)
- Is the result correct? yes
- Are the experienced problems and solutions described well? no

**Comment by Rolfsijtema** [comment]
Added sources and Overcome challanges
