### ISSUE TITLE
Feedback Request: AWS11 Elastic Load Balancing (ELB) & Auto Scaling

### ISSUE THREAD

**Issue by Rolfsijtema** [TechGrounds-Cloud8/cloud8-Rolfsijtema#28]
**Feedback Request: Elastic Load Balancing (ELB) & Auto Scaling**
Permalink to file: [[LINK](https://github.com/TechGrounds-Cloud8/cloud8-Rolfsijtema/blob/8be0dd93043267ca9ce7ddb3deb672b496630e8a/week5cloud8/AWS-11%20(ELB)%20&%20Auto%20Scaling.md)]

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Killian97** [comment]
you could read [where are metrics stored](https://aws.amazon.com/cloudwatch/faqs/). overal well done looks good.
i know you have done it but you miss a screenshot to prove that your auto scaler worked. the screenshots for the 2 automatically made EC2 instances

**Comment by archana-sekarr** [comment]
**Summary**
- Does the summary describe the subject matter fully? yes
- Is the summary written in own words? yes
- Is there crucial information missing in the summary? no
- Is the description clear enough? yes

**Key Terminology**
- Are there missing key terms? no
- Are the key terms explained well? yes

**Sources**
- Are the sources mentioned? yes
- Are the mentioned sources correct? yes

**Excercise**
(Where applicable)
- Is the result correct? yes
- Are the experienced problems and solutions described well? yes, but in the end, try to include the screenshots of your activity log to show the auto scaling works

**Comment by Rolfsijtema** [comment]
I added the missing screenshot ;)
