### ISSUE TITLE
Feedback Request: AWS-12 Well Architected Framework

### ISSUE THREAD

**Issue by Rolfsijtema** [TechGrounds-Cloud8/cloud8-Rolfsijtema#29]
**Feedback Request [Well Architected Framework]**
Permalink to file: [[LINK](https://github.com/TechGrounds-Cloud8/cloud8-Rolfsijtema/blob/bdaad696977f15a86aa9dddee1c1924157eb537d/week5cloud8/AWS-12%20Well%20Architected%20Framework%20copy.md)]

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Killian97** [comment]
CROPSS, well done, but dont forget the overcome challenges

**Comment by sasudi90** [comment]
Looks good Rolf, got the design principles all summed up. Think u won't forget 'Cropps' after shouting it for 4 times at the key terminology. Fill in your challenges btw :)

**Comment by QuincyTjia** [comment]
**Summary**
- Does the summary describe the subject matter fully? yes
- Is the summary written in own words? yes
- Is there crucial information missing in the summary? no
- Is the description clear enough? yes

**Key Terminology**
- Are there missing key terms? no
- Are the key terms explained well? yes

**Sources**
- Are the sources mentioned? yes
- Are the mentioned sources correct? yes

**Excercise**
(Where applicable)
- Is the result correct? yes
- Are the experienced problems and solutions described well? no, you didn't fill it in

**Comment by Rolfsijtema** [comment]
Challenges done, ; None ;)
