### ISSUE TITLE
Feedback Request:git2 markdown

### ISSUE THREAD

**Issue by Rolfsijtema** [TechGrounds-Cloud8/cloud8-Rolfsijtema#3]
**Feedback Request [git2markdown]**
Permalink to file: [git2markdown](https://github.com/TechGrounds-Cloud8/cloud8-Rolfsijtema/blob/main/week1cloud8/git02markdown.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by abdeslamazhir** [comment]
Summary

Does the summary describe the subject matter fully? yes
Is the summary written in own words? yes
Is there crucial information missing in the summary? no
Is the description clear enough? yes
Key Terminology

Are there missing key terms? no
Are the key terms explained well? yes
Sources

Are the sources mentioned? yes
Are the mentioned sources correct? yes
Excercise
(Where applicable)

Is the result correct? yes
Are the experienced problems and solutions described well? yes

**Comment by sasudi90** [comment]
Inhoud is goed, opmaak mag iets netter.
