### ISSUE TITLE
Feedback Request: IAM AWS Cloudwatch DynamoDB AWS Lambda SNS, SQS, Event Bridge

### ISSUE THREAD

**Issue by Rolfsijtema** [TechGrounds-Cloud8/cloud8-Rolfsijtema#32]
**Feedback Request [ IAM AWS Cloudwatch DynamoDB AWS Lambda SNS, SQS, Event Bridge]**
Permalink to file: [[LINK](https://github.com/TechGrounds-Cloud8/cloud8-Rolfsijtema/blob/e96eeea9cbe1c4e7feb41796d30e34fce28ba769/week6cloud8/AWS-14%20practical.md)]

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers..

**Comment by QuincyTjia** [comment]
**Summary**
- Does the summary describe the subject matter fully? y
- Is the summary written in own words? y
- Is there crucial information missing in the summary? n
- Is the description clear enough? y

**Key Terminology**
- Are there missing key terms? y, maybe put in what actually is a NoSQl  instead what it means etc.
- Are the key terms explained well? y

**Sources**
- Are the sources mentioned? y
- Are the mentioned sources correct? y
- 
**Excercise**
(Where applicable)
- Is the result correct? y, but if you have some spare time next week, I will advice to do the practical parts of the last subjects. You will understand it a lot better then.
- Are the experienced problems and solutions described well? n
