### ISSUE TITLE
Feedback Request:OSI/TCP/IP

### ISSUE THREAD

**Issue by Rolfsijtema** [TechGrounds-Cloud8/cloud8-Rolfsijtema#4]
**Feedback Request [NWT-01 OSI/TCP/IP]**
Permalink to file: https://github.com/TechGrounds-Cloud8/cloud8-Rolfsijtema/blob/main/week2cloud8/OSI%20TCP%20IP.md

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by pprasing** [comment]
**Summary**
- Does the summary describe the subject matter fully?yes
- Is the summary written in own words? yes
- Is there crucial information missing in the summary? how about the challenges?
- Is the description clear enough? yes

**Key Terminology**
- Are there missing key terms? how about bottom up and top down approaches?
- Are the key terms explained well? yes

**Sources**
- Are the sources mentioned? yes
- Are the mentioned sources correct? yes

**Excercise**
(Where applicable)
- Is the result correct? yes was just a reading/learning exercise
- Are the experienced problems and solutions described well? yes

**Comment by sasudi90** [comment]
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms? no
- Are the key terms explained well? yes

**Sources**
- Are the sources mentioned? yes
- Are the mentioned sources correct? yes

**Excercise**
(Where applicable)
- Is the result correct? yes
- Are the experienced problems and solutions described well? no
