### ISSUE TITLE
Feedback Request: NTW-02 NETWORK Devices

### ISSUE THREAD

**Issue by Rolfsijtema** [TechGrounds-Cloud8/cloud8-Rolfsijtema#5]
**Feedback Request [NWT-02 network Devices]**
Permalink to file: https://github.com/TechGrounds-Cloud8/cloud8-Rolfsijtema/blob/main/week2cloud8/NTW-02%20Network%20Devices.md

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by pprasing** [comment]
**Summary**
- Does the summary describe the subject matter fully? yes
- Is the summary written in own words? yes, dutch and English ;)
- Is there crucial information missing in the summary? no
- Is the description clear enough? yes

**Key Terminology**
- Are there missing key terms? no
- Are the key terms explained well? yes
 
**Sources**
- Are the sources mentioned?yes
- Are the mentioned sources correct? yes

**Excercise**
(Where applicable)
- Is the result correct? yes, it's not the exercise, but look at which devices are in what layer of the OSI model
- Are the experienced problems and solutions described well? yes

**Comment by sasudi90** [comment]
**Summary**
- Does the summary describe the subject matter fully? yes
- Is the summary written in own words? yes
- Is there crucial information missing in the summary? no
- Is the description clear enough? yes

**Key Terminology**
- Are there missing key terms? no
- Are the key terms explained well? yes

**Sources**
- Are the sources mentioned? yes
- Are the mentioned sources correct? yes

**Excercise**
(Where applicable)
- Is the result correct? yes, but it would be complete if you paste your own DHCP server configuration and not just the theory behind it.
- Are the experienced problems and solutions described well? yes
