### ISSUE TITLE
Feedback Request: Counting in Binary and Hex

### ISSUE THREAD

**Issue by Rolfsijtema** [TechGrounds-Cloud8/cloud8-Rolfsijtema#7]
**Feedback Request [Counting in Binary and Hex]**
Permalink to file: [[LINK]](https://github.com/TechGrounds-Cloud8/cloud8-Rolfsijtema/blob/68bc852c9d48b71eac541a940ee8c629f2b1aa67/week2cloud8/NWT-04%20Counting%20in%20Binary%20and%20Hex.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by pprasing** [comment]
**Summary**
- Does the summary describe the subject matter fully? yes
- Is the summary written in own words? yes
- Is there crucial information missing in the summary?no
- Is the description clear enough? yes

**Key Terminology**
- Are there missing key terms? no
- Are the key terms explained well? yes

**Sources**
- Are the sources mentioned? yes
- Are the mentioned sources correct? yes

**Excercise**
(Where applicable)
- Is the result correct? don't see the results of the exercise
- Are the experienced problems and solutions described well? yes

**Comment by sasudi90** [comment]
**Summary**
- Does the summary describe the subject matter fully? y
- Is the summary written in own words? y
- Is there crucial information missing in the summary? n 
- Is the description clear enough? y

**Key Terminology**
- Are there missing key terms? n 
- Are the key terms explained well? y

**Sources**
- Are the sources mentioned? y
- Are the mentioned sources correct? y

**Excercise**
(Where applicable)
- Is the result correct? mis de uitwerking.
- Are the experienced problems and solutions described well? y

**Comment by Acron0815** [comment]
Summary

Does the summary describe the subject matter fully? yes
Is the summary written in own words? yes
Is there crucial information missing in the summary? no
Is the description clear enough? yes
Key Terminology

Are there missing key terms? no
Are the key terms explained well? yes very well !
Sources

Are the sources mentioned? The references are interesting
Are the mentioned sources correct? yes
Excercise
(Where applicable)

Are the experienced problems and solutions described well? yes

**Comment by Rolfsijtema** [comment]
Results toegevoegd
