### ISSUE TITLE
Feedback Request: IP-adressing

### ISSUE THREAD

**Issue by Rolfsijtema** [TechGrounds-Cloud8/cloud8-Rolfsijtema#8]
**Feedback Request IPadressing**
Permalink to file: [[LINK](https://github.com/TechGrounds-Cloud8/cloud8-Rolfsijtema/blob/e39d620a8f0ff6af2943ab901eed44c302b45d95/week2cloud8/NWT-05%20IP%20adressing.md)]

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by pprasing** [comment]
**Summary**
- Does the summary describe the subject matter fully? yes
- Is the summary written in own words? yes , look at the language. You're writing Dutch and English
- Is there crucial information missing in the summary? no
- Is the description clear enough? yes

**Key Terminology**
- Are there missing key terms? no
- Are the key terms explained well? yes

**Sources**
- Are the sources mentioned? yes
- Are the mentioned sources correct? yes

**Excercise**
(Where applicable)
- Is the result correct? yes, except that all your devices have an private ip address. notice that you're writing that your computer has a public ip address, but there is only 1 public ip address for all of your devices
- Are the experienced problems and solutions described well?yes

**Comment by sasudi90** [comment]
**Summary**
- Does the summary describe the subject matter fully? y
- Is the summary written in own words? y
- Is there crucial information missing in the summary? n
- Is the description clear enough? y

**Key Terminology**
- Are there missing key terms? n
- Are the key terms explained well? y

**Sources**
- Are the sources mentioned? y 
- Are the mentioned sources correct? y

**Excercise**
(Where applicable)
- Is the result correct? read question 2 again :D
- Are the experienced problems and solutions described well? y

Uniformiteit in templates please

**Comment by Rolfsijtema** [comment]
I changed my answer on question 2, we discussed this and it is clear. thanx

**Comment by Acron0815** [comment]
Summary

Does the summary describe the subject matter fully? yes
Is the summary written in own words? yes
Is there crucial information missing in the summary? no
Is the description clear enough? yes
Key Terminology

Are there missing key terms? no
Are the key terms explained well? yes very well !
Sources

Are the sources mentioned? The references are interesting
Are the mentioned sources correct? yes
Excercise
(Where applicable)

Are the experienced problems and solutions described well? yes
